import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.rockyridgesfarm.com/');
  await page.getByRole('banner').getByRole('link', { name: 'Rocky Ridges Farm Organic' }).click();
  await page.getByRole('link', { name: 'Shop', exact: true }).click();
  await page.getByRole('link', { name: 'About' }).click();
  await page.getByRole('link', { name: 'Contact', exact: true }).click();
  await page.getByRole('link', { name: 'Home' }).click();
  await page.getByRole('heading', { name: 'Fresh from Rocky Ridges Farm' }).click();
  await page.getByText('Experience the taste of').click();
  await page.getByRole('link', { name: 'Our Story' }).click();
  await page.getByRole('link', { name: 'Shop Now' }).click();
  await page.getByRole('button', { name: 'Fresh Vegetables(4)' }).click();
  await page.getByRole('link', { name: 'Fresh Carrots Fresh' }).getByLabel('Add to cart').click();
  await page.getByRole('button', { name: 'Seasonal Fruits(14)' }).click();
  await page.getByRole('link', { name: 'Apples Seasonal Fruits Apples' }).getByLabel('Add to cart').click();
  await page.getByRole('link', { name: 'Avocados (Hass) Seasonal' }).getByLabel('Add to cart').click();
  await page.getByRole('button', { name: 'Tubers & Roots(3)' }).click();
  await page.getByRole('link', { name: 'Beetroot Tubers & Roots' }).getByLabel('Add to cart').click();
  await page.getByRole('link', { name: 'Irish Potatoes Tubers & Roots' }).getByLabel('Add to cart').click();
  await page.getByRole('button', { name: 'Herbs & Spices(3)' }).click();
  await page.getByRole('link', { name: 'Dhania (Coriander) Herbs &' }).getByLabel('Add to cart').click();
  await page.getByRole('link', { name: 'Garlic Herbs & Spices Garlic' }).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button').nth(2).click();
  await page.getByText('Quantity:3Add to Cart — KES').click();
  await page.getByRole('button', { name: 'Add to Cart — KES' }).click();
  await page.getByRole('link', { name: 'Cart', exact: true }).click();
  await page.getByRole('button', { name: 'Remove item' }).nth(3).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('link', { name: 'Proceed to Checkout' }).click();
  await page.locator('form').getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Terms & Conditions' }).click();
  await page.getByRole('complementary').getByRole('link', { name: 'FAQ' }).click();
  await page.getByRole('button', { name: 'What areas do you deliver to?' }).click();
  await page.getByRole('link', { name: 'WhatsApp' }).click();
  await page.goto('https://www.rockyridgesfarm.com/help/faq/');
  await page.getByRole('button', { name: 'When will my order be' }).click();
  await page.getByText('We offer same-day delivery').click();
  await page.getByRole('complementary').getByRole('link', { name: 'Privacy Policy' }).click();
  await page.getByRole('complementary').getByRole('link', { name: 'Refunds & Returns' }).click();
  await page.getByRole('complementary').getByRole('link', { name: 'Delivery Policy' }).click();
  await page.getByRole('link', { name: 'support@rockyridge.co.ke' }).click();
});